apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.nameOverride }}
  template:
    metadata:
      labels:
        app: {{ .Values.tag.app }}
        version: {{ .Values.tag.version }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.nameOverride }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.environment }}
        env:
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: web
          containerPort: 6601
        # Add the liveness probe below
        livenessProbe:
          tcpSocket:
            port: 3000 # or the port number your app listens to
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1

      imagePullSecrets:
      - name: regcredio
