apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}-service
  labels:
    app: {{ .Values.nameOverride }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.tag.app }}
  ports:
    - name: http
      protocol: TCP
      port: 6601
      targetPort: 6601
