replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/learningocean-431110/docker-images/dating-backend
  tag: development
  pullPolicy: Always

imagePullSecrets:
  - name: regcredio

tag:
  app: dating-backend
  version: v1

nameOverride: dating-backend
fullnameOverride: dating-backend

resources: {}

environment: []



