replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/learningocean-431110/docker-images/dating-backend
  tag: "00b980bf0274af61c26640a4fee4507774dbea0b"
  pullPolicy: Always

imagePullSecrets:
  - name: regcredio

tag:
  app: dating-backend
  version: v1

nameOverride: dating-backend
fullnameOverride: dating-backend

resources: {}

environment: []

affinity: {}
