apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
  labels:
    app: {{ .Values.nameOverride }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.tag.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.tag.app }}
        version: {{ .Values.tag.version }}
    spec:
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ .Values.nameOverride }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.environment }}
        env:
          {{- toYaml .Values.environment | nindent 10 }}
        {{- end }}
        ports:
        - name: web
          containerPort: 6601
        livenessProbe:
          tcpSocket:
            port: 6601
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 1
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
