apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameOverride }}-service
  labels:
    app: {{ .Values.nameOverride }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.tag.app }}
  ports:
    - name: http
      protocol: TCP
      port: 6601
      targetPort: 6601

---

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: backend
  namespace: default
spec:
  hosts:
    - backend.gouravn.info
  gateways:
    - istio-system/main-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: dating-backend-service.default.svc.cluster.local
            port:
              number: 6601
